INSERT INTO invoice_status(id_invoice_status,invoice_status_name) VALUES(1,'PAID');
INSERT INTO invoice_status(id_invoice_status,invoice_status_name) VALUES(2,'UNPAID');
INSERT INTO tipe_pengeluaran(id_tipe_pengeluaran,tipe_pengeluaran_name) VALUES(1,'VENDOR');
INSERT INTO tipe_pengeluaran(id_tipe_pengeluaran,tipe_pengeluaran_name) VALUES(2,'OPERATION');
INSERT INTO tipe_pengeluaran(id_tipe_pengeluaran,tipe_pengeluaran_name) VALUES(3,'TAX');
INSERT INTO project_status(id_project_status,project_status_name) VALUES(1,'DONE');
INSERT INTO project_status(id_project_status,project_status_name) VALUES(2,'REJECTED');
INSERT INTO project_status(id_project_status,project_status_name) VALUES(3,'IN PROGRESS');
INSERT INTO karyawan(id_karyawan,karyawan_nama,karyawan_email) VALUES(1,'Rebecca Hall','rebecca.hall@king.com');
INSERT INTO karyawan(id_karyawan,karyawan_nama,karyawan_email) VALUES(2,'Edwin Harding','edwin.harding@fox.com');
INSERT INTO client(id_client,client_nama,client_email,client_company) VALUES(1,'James Jackson','james.jackson@mitchell.net','Wilson, Joseph and Stuart');
INSERT INTO client(id_client,client_nama,client_email,client_company) VALUES(2,'Patricia Schroeder','patricia.schroeder@harrison.biz','Scott-Bentley');